services:
  localstack:
    image: localstack/localstack:latest
    container_name: normal_localstack
    ports:
      - "4567:4566"   # AWS API (different port from knob)
      - "8081:8080"   # Web UI (different port from knob)
      - "2223:2222"   # SSH access placeholder (different port from knob)
    environment:
      - SERVICES=s3,ec2
      - DEFAULT_REGION=us-east-1
      - LOCALSTACK_API_KEY=YOUR_API_KEY   # Required for Pro/Starter
      - EC2_VM_MANAGER=docker
      - LOCALSTACK_WEB_UI=true
    volumes:
      - ./localstack-init/ready.d:/etc/localstack/init/ready.d

  write:
    build: ./services/write
    ports:
      - "6001:5001"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - localstack

  read:
    build: ./services/read
    ports:
      - "6002:5002"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - localstack

  reencrypt:
    build: ./services/reencrypt
    ports:
      - "6003:5003"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - localstack
  client_db:
    build: ./services/client_db
    ports:
      - "6004:5004"

  web:
    image: python:3.11-slim
    working_dir: /gui
    volumes:
      - ./gui:/gui
    ports:
      - "8002:8000"
    command: python -m http.server 8000
    container_name: normal_web